env:
  heroku: false
categories:
  _defaults:
    #font: Russo One
    font: false
    theme: big_brother
    number_of_tweets: 3
    disconnect_warning: Connection to server lost
    time_per_slide: 5000
    slide_transition_time: 400
    greeting_time: 1000
    chance_of_slogan: 5
    show_on_menu: true
  rig:
    title: RIG
    font: false
    theme: default
    number_of_tweets: 10
    show_on_menu: false
    time_per_slide: 10000
    slide_transition_time: 1000
    greeting_time: 2000
    screen_names:
      - antimega
      - benterret
      - iotwatch
      - jamesbridle
      - philgyford
      - tomtaylor
      - undermanager
  us:
    title: United States
    screen_names:
      - tomcoates
      - mattb
    burn_in_text: TODO
    greetings:
      - Attention<br>folks!
    slogans:
      - Believe in America
      - Country first
      - Forward
      - If you see something, say something
      - Stay the course
      - Yes we can
  uk:
    title: United Kingdom
    screen_names:
      - philgyfordtest
      - philgyford
    burn_in_text: Go home or face arrest
    greetings:
      - Attention<br>subjects!
    slogans:
      - Are you thinking what we’re thinking?
      - You’ve had your debate
      - Go home or face arrest

