env:
  heroku: false
ui:
  # How many tweets do we cycle through?
  number_of_tweets: 3
categories:
  us:
    name: United States
    greeting: Attention<br />folks!
    burn_in_text: TODO
    disconnect_warning: You are no longer connected. TODO
    screen_names:
      - tomcoates
      - mattb
  uk:
    name: United Kingdom
    greeting: Attention<br />subjects!
    burn_in_text: Go home or face arrest
    disconnect_warning: You are no longer connected. Reconnect or face arrest.
    screen_names:
      - philgyfordtest
      - philgyford

