env:
  heroku: false
ui:
  # How many tweets do we cycle through?
  number_of_tweets: 3
categories:
  uk:
    name: United Kingdom
    greeting: ATTENTION SUBJECTS!
    accounts:
      - 2030131 # philgyfordtest
      - 12552 # philgyford
      - 12514 # tomcoates

