env:
  heroku: false
ui:
  # How many tweets do we cycle through?
  number_of_tweets: 3
categories:
  uk:
    name: United Kingdom
    greeting: Attention<br />subjects!
    burn_in_text: Go home or face arrest
    disconnect_warning: You are no longer connected. Reconnect or face arrest.
    accounts:
      - 2030131 # philgyfordtest
      #- 12552 # philgyford
      #- 12514 # tomcoates

