env:
  heroku: false
categories:
  _defaults:
    font: Russo One
    theme: big_brother
    number_of_tweets: 3
    disconnect_warning: Connection to server lost
    time_per_slide: 5000
    slide_transition_time: 400
    chance_of_slogan: 5
    show_on_menu: true
  us:
    title: United States
    screen_names:
      - tomcoates
      - mattb
    burn_in_text: TODO
    greetings:
      - Attention<br>folks!
    slogans:
      - Believe in America
      - Country first
      - Forward
      - If you see something, say something
      - Stay the course
      - Yes we can
  uk:
    title: United Kingdom
    screen_names:
      - philgyfordtest
      - philgyford
    burn_in_text: Go home or face arrest
    greetings:
      - Attention<br>subjects!
    slogans:
      - Are you thinking what we’re thinking?
      - You’ve had your debate
      - Go home or face arrest

