env:
  heroku: false
categories:
  _defaults:
    font: Russo One
    theme: big_brother
    number_of_tweets: 3
    time_per_slide: 5000
    slide_transition_time: 400
    show_on_menu: true
  us:
    title: United States
    greeting: Attention<br />folks!
    burn_in_text: TODO
    disconnect_warning: You are no longer connected. TODO
    screen_names:
      - tomcoates
      - mattb
  uk:
    title: United Kingdom
    greeting: Attention<br />subjects!
    burn_in_text: Go home or face arrest
    disconnect_warning: You are no longer connected. Reconnect or face arrest.
    screen_names:
      - philgyfordtest
      - philgyford

