env:
  heroku: false
categories:
  _defaults:
    font: Russo One
    theme: big_brother
    number_of_tweets: 12
    disconnect_warning: Connection to server lost
    time_per_slide: 8000
    slide_transition_time: 1000
    greeting_time: 2000
    chance_of_slogan: 5
    show_on_menu: true
  rig:
    title: RIG
    font: false
    theme: default
    show_on_menu: false
    greetings:
      - Ahoy!
      - Hello
    screen_names:
      - antimega
      - benterret
      - iotwatch
      - jamesbridle
      - philgyford
      - tomtaylor
      - undermanager
  us:
    title: United States
    screen_names:
      - barackobama
      - CDCemergency
      - deptofdefense
      - readygov
      - tsablogteam
      - usairforce
      - usarmy
      - uscis
      - usnavy
      - whitehouse
    burn_in_text: If you see something, say something
    greetings:
      - Attention<br>folks!
    slogans:
      - Believe in America
      - Country first
      - Forward
      - If you see something, say something
      - Stay the course
      - Yes we can
  uk:
    title: United Kingdom
    screen_names:
      - david_cameron
      - DefenceHQ
      - dwppressoffice
      - hmrcgovuk
      - mojgovuk
      - number10gov
      - transportgovuk
      - ukhomeoffice
    burn_in_text: Go home or face arrest
    greetings:
      - Attention<br>subjects!
    slogans:
      - Are you thinking what we’re thinking?
      - You’ve had your debate
      - Go home or face arrest
      - Hardworking families

